### ISSUE TITLE
Basic question 

### ISSUE THREAD

**Issue by kwccoin** [Satrat/lets-go#1]
May I ask what is slack in the set section? I assume size is 13x13. 

Also, want to adopt it as a go board recorder and may be a reader or analyses of go movement. Is this to go or you may have other source?  

Thanks for any advice.

**Comment by Satrat** [comment]
Hi there! Slack is how many pixels the center of the game piece can be from the cross on the board and still be recognized at that position. Depending on how zoomed in your camera is you will probably need to adjust this value. The size is 13 by default but can be adjusted.

This project processes a live video stream from a webcam and doesn't save the video output, but you could definitely adapt the code to act as a recorder. Try looking into the `VideoWriter` class in OpenCV.
